namespace PL_CANONF1

/-! Control stack, collusion layer, T6: a verified canonicaliser for a toy imperative language.
A trusted mediator that applies `canon` erases exactly three declared syntactic freedoms:
(a) `for` vs `while` loop form, (b) association of `;`, (c) the names of local variables.
(i) It preserves semantics.
(ii) `canon p = canon q ↔ p ≈ q`, where `≈` is generated by (a), (b) and (c).
(iii) Hence, if attacks and honeypots induce the same law on `≈`-classes, the mediated laws are equal:
every monitor's pass rate is identical on both, so signals carried only by these three freedoms contribute
nothing. Other freedoms (operand order, statement order, dead code, constants) remain channels.

The `for` here is restricted: statement init/step, a pure condition, no break/continue, no block scope.
Its semantics is the C11 §6.8.5.3 equation `init; while cond { body; step }`. -/

inductive AExp where
  | lit (n : ℤ) | var (v : ℕ) | add (a b : AExp) | sub (a b : AExp) | mul (a b : AExp)
  deriving DecidableEq

inductive BExp where
  | lt (a b : AExp) | eq (a b : AExp) | not (b : BExp) | and (b c : BExp)
  deriving DecidableEq

inductive Stmt where
  | skip
  | assign (v : ℕ) (a : AExp)
  | seq (s t : Stmt)
  | ite (b : BExp) (s t : Stmt)
  | while (b : BExp) (s : Stmt)
  /-- C-style `for (init; cond; step) body` -/
  | cfor (init : Stmt) (cond : BExp) (step : Stmt) (body : Stmt)
  deriving DecidableEq

/-- variables `0 .. nparams-1` are the parameters (bound to the inputs); all others are locals,
initialised to `0`. -/
structure Prog where
  nparams : ℕ
  body : Stmt
  ret : AExp
  deriving DecidableEq

abbrev State := ℕ → ℤ

def AExp.eval : AExp → State → ℤ
  | .lit n, _ => n
  | .var v, σ => σ v
  | .add a b, σ => a.eval σ + b.eval σ
  | .sub a b, σ => a.eval σ - b.eval σ
  | .mul a b, σ => a.eval σ * b.eval σ

def BExp.eval : BExp → State → Bool
  | .lt a b, σ => decide (a.eval σ < b.eval σ)
  | .eq a b, σ => decide (a.eval σ = b.eval σ)
  | .not b, σ => !b.eval σ
  | .and b c, σ => b.eval σ && c.eval σ

/-- relational big-step semantics; `for` follows C (C11 §6.8.5.3, no `continue`):
`for (i; c; st) b` behaves as `i; while c { b; st }`. -/
inductive Exec : Stmt → State → State → Prop where
  | skip (σ) : Exec .skip σ σ
  | assign (v a σ) : Exec (.assign v a) σ (Function.update σ v (a.eval σ))
  | seq (s t σ σ' σ'') : Exec s σ σ' → Exec t σ' σ'' → Exec (.seq s t) σ σ''
  | iteT (b s t σ σ') : b.eval σ = true → Exec s σ σ' → Exec (.ite b s t) σ σ'
  | iteF (b s t σ σ') : b.eval σ = false → Exec t σ σ' → Exec (.ite b s t) σ σ'
  | whileT (b s σ σ' σ'') : b.eval σ = true → Exec s σ σ' → Exec (.while b s) σ' σ'' →
      Exec (.while b s) σ σ''
  | whileF (b s σ) : b.eval σ = false → Exec (.while b s) σ σ
  | cfor (i c st body σ σ') : Exec (.seq i (.while c (.seq body st))) σ σ' →
      Exec (.cfor i c st body) σ σ'

def initState (k : ℕ) (ins : List ℤ) : State := fun v => if v < k then ins.getD v 0 else 0

/-- `p` maps inputs `ins` to output `out` (some terminating run). -/
def Runs (p : Prog) (ins : List ℤ) (out : ℤ) : Prop :=
  ins.length = p.nparams ∧ ∃ σ', Exec p.body (initState p.nparams ins) σ' ∧ p.ret.eval σ' = out

/-! ### The canonicaliser (executable) -/

def desugar : Stmt → Stmt
  | .skip => .skip
  | .assign v a => .assign v a
  | .seq s t => .seq (desugar s) (desugar t)
  | .ite b s t => .ite b (desugar s) (desugar t)
  | .while b s => .while b (desugar s)
  | .cfor i c st body => .seq (desugar i) (.while c (.seq (desugar body) (desugar st)))

def AExp.rename (f : ℕ → ℕ) : AExp → AExp
  | .lit n => .lit n
  | .var v => .var (f v)
  | .add a b => .add (a.rename f) (b.rename f)
  | .sub a b => .sub (a.rename f) (b.rename f)
  | .mul a b => .mul (a.rename f) (b.rename f)

def BExp.rename (f : ℕ → ℕ) : BExp → BExp
  | .lt a b => .lt (a.rename f) (b.rename f)
  | .eq a b => .eq (a.rename f) (b.rename f)
  | .not b => .not (b.rename f)
  | .and b c => .and (b.rename f) (c.rename f)

def Stmt.rename (f : ℕ → ℕ) : Stmt → Stmt
  | .skip => .skip
  | .assign v a => .assign (f v) (a.rename f)
  | .seq s t => .seq (s.rename f) (t.rename f)
  | .ite b s t => .ite (b.rename f) (s.rename f) (t.rename f)
  | .while b s => .while (b.rename f) (s.rename f)
  | .cfor i c st body => .cfor (i.rename f) (c.rename f) (st.rename f) (body.rename f)

def Prog.rename (f : ℕ → ℕ) (p : Prog) : Prog :=
  ⟨p.nparams, p.body.rename f, p.ret.rename f⟩

/-- variable occurrences in pre-order -/
def AExp.occ : AExp → List ℕ
  | .lit _ => []
  | .var v => [v]
  | .add a b => a.occ ++ b.occ
  | .sub a b => a.occ ++ b.occ
  | .mul a b => a.occ ++ b.occ

def BExp.occ : BExp → List ℕ
  | .lt a b => a.occ ++ b.occ
  | .eq a b => a.occ ++ b.occ
  | .not b => b.occ
  | .and b c => b.occ ++ c.occ

def Stmt.occ : Stmt → List ℕ
  | .skip => []
  | .assign v a => v :: a.occ
  | .seq s t => s.occ ++ t.occ
  | .ite b s t => b.occ ++ s.occ ++ t.occ
  | .while b s => b.occ ++ s.occ
  | .cfor i c st body => i.occ ++ c.occ ++ st.occ ++ body.occ

def Prog.occ (p : Prog) : List ℕ := p.body.occ ++ p.ret.occ

/-- distinct elements in order of first occurrence -/
def firstOcc (l : List ℕ) : List ℕ :=
  l.foldl (fun acc v => if v ∈ acc then acc else acc ++ [v]) []

/-- locals of `p` in order of first occurrence -/
def Prog.locals (p : Prog) : List ℕ := (firstOcc p.occ).filter (fun v => p.nparams ≤ v)

/-- parameters keep their index; the `i`-th local (by first occurrence) becomes `nparams + i` -/
def Prog.canonMap (p : Prog) (v : ℕ) : ℕ :=
  if v < p.nparams then v else p.nparams + p.locals.idxOf v

/-- append `t` at the end of the right spine of `s` (right-associated sequencing) -/
def Stmt.append : Stmt → Stmt → Stmt
  | .seq a b, t => .seq a (b.append t)
  | s, t => .seq s t

/-- right-associate every `;` -/
def flatten : Stmt → Stmt
  | .skip => .skip
  | .assign v a => .assign v a
  | .seq s t => (flatten s).append (flatten t)
  | .ite b s t => .ite b (flatten s) (flatten t)
  | .while b s => .while b (flatten s)
  | .cfor i c st body => .cfor (flatten i) c (flatten st) (flatten body)

def desugarProg (p : Prog) : Prog := ⟨p.nparams, flatten (desugar p.body), p.ret⟩

def canon (p : Prog) : Prog :=
  let d := desugarProg p
  d.rename d.canonMap

/-! ### The declared syntactic equivalence -/

/-- one `for → while` rewrite or one `;`-reassociation, at any position -/
inductive ForStep : Stmt → Stmt → Prop where
  | here (i c st body) : ForStep (.cfor i c st body) (.seq i (.while c (.seq body st)))
  | assoc (s t u) : ForStep (.seq (.seq s t) u) (.seq s (.seq t u))
  | seqL (s s' t) : ForStep s s' → ForStep (.seq s t) (.seq s' t)
  | seqR (s t t') : ForStep t t' → ForStep (.seq s t) (.seq s t')
  | iteL (b s s' t) : ForStep s s' → ForStep (.ite b s t) (.ite b s' t)
  | iteR (b s t t') : ForStep t t' → ForStep (.ite b s t) (.ite b s t')
  | whileB (b s s') : ForStep s s' → ForStep (.while b s) (.while b s')
  | forI (i i' c st body) : ForStep i i' → ForStep (.cfor i c st body) (.cfor i' c st body)
  | forSt (i c st st' body) : ForStep st st' → ForStep (.cfor i c st body) (.cfor i c st' body)
  | forBody (i c st body body') : ForStep body body' →
      ForStep (.cfor i c st body) (.cfor i c st body')

/-- a renaming admissible for `p`: fixes parameters, keeps locals local, injective on the
variables of `p` -/
def Admissible (f : ℕ → ℕ) (p : Prog) : Prop :=
  (∀ v ∈ p.occ, v < p.nparams → f v = v) ∧
  (∀ v ∈ p.occ, p.nparams ≤ v → p.nparams ≤ f v) ∧
  (∀ v ∈ p.occ, ∀ w ∈ p.occ, f v = f w → v = w)

inductive Step : Prog → Prog → Prop where
  | loop (k body body' ret) : ForStep body body' → Step ⟨k, body, ret⟩ ⟨k, body', ret⟩
  | ren (f p) : Admissible f p → Step p (p.rename f)

/-- `p ≈ q` -/
def SynEquiv : Prog → Prog → Prop := Relation.EqvGen Step

open Classical in
def Claim : Prop :=
  -- (i) semantics preservation
  (∀ p ins out, Runs (canon p) ins out ↔ Runs p ins out) ∧
  -- (ii) unique normal form modulo the declared equivalence
  (∀ p q, canon p = canon q ↔ SynEquiv p q) ∧
  -- (iii) mediated laws: if attack and honeypot laws on a finite set of programs agree on every
  -- `≈`-class, the canonicalised (mediated) laws are equal
  (∀ (X : Type) [Fintype X] (prog : X → Prog) (PA PH : X → ℝ),
    (∀ p, ∑ x ∈ Finset.univ.filter (fun x => SynEquiv (prog x) p), PA x =
          ∑ x ∈ Finset.univ.filter (fun x => SynEquiv (prog x) p), PH x) →
    ∀ z : Prog, ∑ x ∈ Finset.univ.filter (fun x => canon (prog x) = z), PA x =
                ∑ x ∈ Finset.univ.filter (fun x => canon (prog x) = z), PH x)

/-- Non-vacuity: a `for` program and a `while` program with different local names are identified
and compute 0+1+2 = 3 on input 3, while a semantically different program is not identified. -/
def Witness : Prop :=
  let pFor : Prog := ⟨1, .seq (.assign 7 (.lit 0))
      (.cfor (.assign 5 (.lit 0)) (.lt (.var 5) (.var 0)) (.assign 5 (.add (.var 5) (.lit 1)))
             (.assign 7 (.add (.var 7) (.var 5)))), .var 7⟩
  let pWhile : Prog := ⟨1, .seq (.assign 2 (.lit 0)) (.seq (.assign 9 (.lit 0))
      (.while (.lt (.var 9) (.var 0))
        (.seq (.assign 2 (.add (.var 2) (.var 9))) (.assign 9 (.add (.var 9) (.lit 1)))))), .var 2⟩
  let pOther : Prog := ⟨1, .assign 2 (.add (.var 0) (.lit 1)), .var 2⟩
  canon pFor = canon pWhile ∧ Runs pFor [3] 3 ∧ canon pFor ≠ canon pOther ∧ ¬ SynEquiv pFor pOther

end PL_CANONF1
