import ControlStack.Families.F2.ChannelInstances
#check ControlStack.ChannelInstances.sc02_accumulated
#check ControlStack.ChannelInstances.rekey_epoch
#print axioms ControlStack.ChannelInstances.sc02_accumulated
#print axioms ControlStack.ChannelInstances.rekey_epoch
