#!/usr/bin/env python3
"""Deterministic, conservative Lean declaration inventory.

Inventory is lexical (not a Lean parser): each declaration is a source-index
record until separately audited. Never promote from filename or compilation
history; reviewed annotations carry their own recorded provenance and assumptions.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DECL = re.compile(r"(?m)^[ \t]*(?:(?:private|protected)\s+)?(?:theorem|lemma)\s+([A-Za-z_][A-Za-z_0-9']*)\b")
ALLOWED = {"SOURCE_ONLY", "PROVED_RECORDED", "VERIFIED_RECORDED", "REVIEWED_RECORDED"}
FAMILIES = {f"F{i}" for i in range(1, 9)}
CLASSES = {"NON_ADAPTIVE", "ADAPTIVE_FEEDBACK", "SHARED_SEED",
           "SIDE_OBSERVING", "CONTENT_ADAPTIVE", "TRACE_ARBITRARY", "UNKNOWN"}


def inventory():
    files = sorted([* (ROOT / "ControlStack").rglob("*.lean"),
                    * (ROOT / "proofs").glob("*.lean"),
                    * (ROOT / "ledger").glob("*.lean")])
    annotations = json.loads((ROOT / "registry/annotations.json").read_text())
    if not isinstance(annotations, dict):
        raise ValueError("registry annotations must be a map")
    rows = []
    seen = set()
    for file in files:
        rel = file.relative_to(ROOT).as_posix()
        src = file.read_text()
        blob = file.read_bytes()
        content_sha = hashlib.sha1(b"blob " + str(len(blob)).encode() + b"\0" + blob).hexdigest()[:12]
        occurrences = {}
        for name in DECL.findall(src):
            occurrences[name] = occurrences.get(name, 0) + 1
            suffix = "" if occurrences[name] == 1 else f"#{occurrences[name]}"
            key = f"{rel}::{name}{suffix}"
            if key in seen:
                raise ValueError(f"duplicate lexical declaration {key}")
            seen.add(key)
            meta = annotations.get(key, {})
            status = meta.get("status", "SOURCE_ONLY")
            family = meta.get("family", "UNMAPPED")
            adversary = meta.get("adversary", "UNKNOWN")
            if status not in ALLOWED or family not in FAMILIES | {"UNMAPPED"} or adversary not in CLASSES:
                raise ValueError(f"{key}: invalid annotation")
            if status != "SOURCE_ONLY" and (family == "UNMAPPED" or adversary == "UNKNOWN"
                    or not meta.get("premises") or not meta.get("record")):
                raise ValueError(f"{key}: recorded result missing scope or provenance")
            rows.append((key, family, ", ".join(meta.get("scenarios", [])) or "—",
                         adversary, "; ".join(meta.get("premises", [])) or "UNMAPPED",
                         status, meta.get("necessity_witness", "NOT_RECORDED"),
                         meta.get("record", "source only"), content_sha))
    stale = set(annotations) - seen
    if stale:
        raise ValueError(f"stale registry annotation(s): {sorted(stale)}")
    return rows


def render():
    rows = inventory()
    lines = [
        "# Theorem registry — generated source inventory",
        "",
        "Generated by `python3 tools/build_registry.py` from current Lean sources and "
        "`registry/annotations.json`. **Not a statement that all inventory entries "
        "are machine-verified.** Lexical declaration scanning may omit unconventional "
        "syntax; an independent Lean environment elaboration check remains required.",
        "",
        f"Declarations indexed: **{len(rows)}**. "
        f"Unclassified adversary: **{sum(x[3] == 'UNKNOWN' for x in rows)}**. "
        f"Source-only: **{sum(x[5] == 'SOURCE_ONLY' for x in rows)}**.",
        "",
        "An annotation's PROVED_RECORDED / VERIFIED_RECORDED is **historical** and "
        "requires independent replay at the exact pinned commit. REVIEWED_RECORDED "
        "is a review, not proof. NO deployment applicability is inferred.",
        "",
        "| File::declaration | Family | Scenarios | Adversary | Premises (summary) | Status | Necessity witness | Record | Git blob SHA1 prefix |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(s).replace("|", "/").replace("\n", " ") for s in row) + " |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    dest = ROOT / "THEOREM-REGISTRY.md"
    text = render()
    if args.check:
        if not dest.exists() or dest.read_text() != text:
            raise SystemExit("THEOREM-REGISTRY.md is stale")
    else:
        dest.write_text(text)
        print(f"wrote {dest}")


if __name__ == "__main__":
    main()
